services:
  - type: web
    name: dramamu-backend
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: dramamu-database
          property: connectionString
      - key: MIDTRANS_SERVER_KEY
        sync: false
      - key: MIDTRANS_CLIENT_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://famous-semolina-e06e90.netlify.app

databases:
  - name: dramamu-database
    databaseName: dramamu_db
    user: dramamu_user
    plan: free
    region: singapore
