[[build]]
  publish = "."
  command = "echo 'No build required - static HTML'"

[[redirects]]
  from = "/"
  to = "/home.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache, no-store, must-revalidate"
